import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const switzerFont = localFont({
  src: "../../public/fonts/switzer/Switzer-Variable.ttf",
  variable: "--font-switzer",
});

const switzerItalic = localFont({
  src: "../../public/fonts/switzer/Switzer-VariableItalic.ttf",
  variable: "--font-switzer-italic",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${switzerFont.variable} ${switzerItalic.variable} antialiased`}
      >
        <div className="relative h-screen">
          <Header className="absolute top-0 left-0 w-full z-10" />
        </div>
        {children}
      </body>
    </html>
  );
}
